import "app/favicon.png"
import "@/node_modules/react-modal-video/css/modal-video.css"
import Aos_Animation from "@/components/elements/AosAnimation"
import "public/assets/css/bootstrap.css"
import "public/assets/css/aos.css"
import "public/assets/css/style.css"
import "public/assets/css/responsive.css"
import 'swiper/css'
import "swiper/css/pagination"
import 'swiper/css/free-mode';
import { urbanist, inter } from '@/lib/font'
export const metadata = {
    title: 'Financer React Next Js Template',
    description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
    return (
        <html lang="en" className={`${urbanist.variable} ${inter.variable}`}>
            <body>
                <Aos_Animation/>
                {children}
            </body>
        </html>
    )
}
